//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 卓越项目.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fang
    {
        public fang()
        {
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string dong { get; set; }
        public Nullable<int> danyuan { get; set; }
        public Nullable<int> louceng { get; set; }
        public Nullable<int> fangjian { get; set; }
        public Nullable<System.DateTime> datetiem { get; set; }
        public Nullable<decimal> up { get; set; }
        public Nullable<decimal> dianliang { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> bossid { get; set; }
    
        public virtual boss boss { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
