//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 卓越项目.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities : DbContext
    {
        public DemoEntities()
            : base("name=DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<boss> boss { get; set; }
        public DbSet<chongzhi> chongzhi { get; set; }
        public DbSet<fang> fang { get; set; }
        public DbSet<zhuce> zhuce { get; set; }
        public DbSet<fankui> fankui { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<order> order { get; set; }
    }
}
