//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 卓越项目.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> bossid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> fangid { get; set; }
        public Nullable<decimal> up { get; set; }
        public Nullable<decimal> now { get; set; }
        public Nullable<decimal> dianjia { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual boss boss { get; set; }
        public virtual fang fang { get; set; }
        public virtual User User { get; set; }
    }
}
