//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 卓越项目.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.chongzhi = new HashSet<chongzhi>();
            this.fang = new HashSet<fang>();
            this.fankui = new HashSet<fankui>();
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string pwd { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<System.DateTime> findtime { get; set; }
        public string url { get; set; }
    
        public virtual ICollection<chongzhi> chongzhi { get; set; }
        public virtual ICollection<fang> fang { get; set; }
        public virtual ICollection<fankui> fankui { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
